/*
 Navicat MySQL Data Transfer

 Source Server         : portal测试环境2.188
 Source Server Type    : MySQL
 Source Server Version : 80026
 Source Host           : 192.168.2.188:3306
 Source Schema         : nnroad_portal

 Target Server Type    : MySQL
 Target Server Version : 80026
 File Encoding         : 65001

 Date: 25/06/2026 09:53:57
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for portal_bill_field_info
-- ----------------------------
DROP TABLE IF EXISTS `portal_bill_field_info`;
CREATE TABLE `portal_bill_field_info`  (
  `field_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `field_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段编码（业务唯一键，同供应商内唯一）',
  `field_name_en` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '英文名称',
  `field_name_cn` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '中文名称',
  `field_type` tinyint NOT NULL DEFAULT 1 COMMENT '字段类型：1语义识别 2计算 3其他库来源 4其他',
  `field_level` int NULL DEFAULT 0 COMMENT '层级（树/分组深度）',
  `parent_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '父字段编码',
  `parent_name_en` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '父字段英文名',
  `is_group` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否分组节点 0否 1是',
  `field_role` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '字段角色（如 input/output/header）',
  `business_category` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务分类',
  `template_zone` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '模板区域（如 Sheet1/区域名）',
  `is_fixed` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否固定列 0否 1是',
  `is_dynamic` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否动态列 0否 1是',
  `display_order` int NULL DEFAULT 0 COMMENT '展示/排序序号',
  `calc_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '计算类型',
  `data_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '数据类型',
  `is_required` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否必填 0否 1是',
  `default_supplier_label` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '供应商侧默认标签/列名',
  `example_source_field` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '示例来源字段（映射参考）',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '说明备注',
  `apply_vendor_ids` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '适用供应商ID JSON 数组',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `create_time` datetime NULL DEFAULT NULL,
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `update_time` datetime NULL DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '系统备注',
  PRIMARY KEY (`field_id`) USING BTREE,
  UNIQUE INDEX `uk_field_code`(`field_code`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 275 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '账单导出字段信息（按供应商）' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of portal_bill_field_info
-- ----------------------------
INSERT INTO `portal_bill_field_info` VALUES (184, 'base_info', 'base_info', '基础信息', 1, 1, NULL, NULL, 1, 'system', NULL, 'fixed_left', 1, 0, 1, 'ignore', 'group', 0, NULL, NULL, NULL, NULL, 'admin', '2026-03-31 16:55:05', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (185, 'pay_period', 'pay_period', '付款日期', 1, 1, NULL, NULL, 1, 'system', NULL, 'fixed_left', 1, 0, 2, 'ignore', 'group', 0, NULL, 'Pay Period', NULL, '[]', 'admin', '2026-03-31 16:55:05', 'admin', '2026-04-07 11:34:07', NULL);
INSERT INTO `portal_bill_field_info` VALUES (186, 'net_income_group', 'net_income_group', 'Net Income', 1, 1, NULL, NULL, 1, 'system', NULL, 'result_zone', 1, 0, 3, 'ignore', 'group', 0, NULL, NULL, NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (187, 'gross_salary', 'gross_salary', 'Gross Salary', 1, 1, NULL, NULL, 1, 'system', NULL, 'income_zone', 1, 0, 4, 'ignore', 'group', 0, NULL, 'Gross Salary', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-07 11:34:49', NULL);
INSERT INTO `portal_bill_field_info` VALUES (188, 'expense_items', 'expense_items', 'Expense Items', 1, 1, NULL, NULL, 1, 'system', NULL, 'expense_zone', 1, 0, 5, 'ignore', 'group', 0, NULL, 'Expense Claim', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-07 11:34:58', NULL);
INSERT INTO `portal_bill_field_info` VALUES (189, 'contribution_items', 'contribution_items', 'Contribution Items', 1, 1, NULL, NULL, 1, 'system', NULL, 'contribution_zone', 1, 0, 6, 'ignore', 'group', 0, NULL, 'Mandatory Contribution', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-07 11:35:08', NULL);
INSERT INTO `portal_bill_field_info` VALUES (190, 'client_code', 'Client Code', '客户编码', 3, 2, 'base_info', NULL, 0, 'fixed', NULL, 'fixed_left', 1, 0, 7, 'direct_input', 'STRING', 1, NULL, 'Client Code', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-07 14:01:22', NULL);
INSERT INTO `portal_bill_field_info` VALUES (191, 'client_name', 'Client Name', '客户名称', 3, 2, 'base_info', NULL, 0, 'fixed', NULL, 'fixed_left', 1, 0, 8, 'direct_input', 'STRING', 1, NULL, 'Client Name', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-07 14:01:35', NULL);
INSERT INTO `portal_bill_field_info` VALUES (192, 'employee_code', 'EE Code', '员工编码', 3, 2, 'base_info', NULL, 0, 'fixed', NULL, 'fixed_left', 1, 0, 9, 'direct_input', 'STRING', 1, NULL, 'EE Code', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 18:41:39', NULL);
INSERT INTO `portal_bill_field_info` VALUES (193, 'employee_name', 'EE Name', '员工姓名', 3, 2, 'base_info', NULL, 0, 'fixed', NULL, 'fixed_left', 1, 0, 10, 'direct_input', 'STRING', 1, NULL, 'EE Name', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 18:41:45', NULL);
INSERT INTO `portal_bill_field_info` VALUES (194, 'pay_period_from', 'From', '发薪月开始日期/ 账单开始日期- 是日期格式（例如2026/6/30）', 1, 2, 'pay_period', NULL, 0, 'fixed', NULL, 'fixed_left', 1, 0, 11, 'direct_input', 'DATE', 1, NULL, 'From', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-02 00:17:45', NULL);
INSERT INTO `portal_bill_field_info` VALUES (195, 'pay_period_to', 'To', '发薪月结束日期/账单结束日期- 是日期格式（例如2026/6/30）', 1, 2, 'pay_period', NULL, 0, 'fixed', NULL, 'fixed_left', 1, 0, 12, 'direct_input', 'DATE', 1, NULL, 'To', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-02 00:18:05', NULL);
INSERT INTO `portal_bill_field_info` VALUES (196, 'net_income', 'Net Income', '实发净收入', 2, 2, 'net_income_group', NULL, 0, 'result', NULL, 'result_zone', 0, 0, 13, 'derived', 'NUMBER', 1, NULL, 'Net Income', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-07 13:57:21', NULL);
INSERT INTO `portal_bill_field_info` VALUES (197, 'adjustment_other', 'Adjustment Other', '其他调整', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 14, 'direct_input', 'NUMBER', 0, NULL, 'Other Adjustments', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (198, 'allowance_car', 'Allowance Car', '车补', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 15, 'direct_input', 'NUMBER', 0, NULL, 'Car Allowance', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (199, 'allowance_communication', 'Allowance Communication', '通讯津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 16, 'direct_input', 'NUMBER', 0, NULL, 'Telephone allowance', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (200, 'allowance_expat', 'Allowance Expat', '外籍生活津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 17, 'direct_input', 'NUMBER', 0, NULL, '外籍生活津贴', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (201, 'allowance_hazard', 'Allowance Hazard', '有毒有害作业津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 18, 'direct_input', 'NUMBER', 0, NULL, '有毒有害作业费', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (202, 'allowance_heat', 'Allowance Heat', '高温津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 19, 'direct_input', 'NUMBER', 0, NULL, '高温费', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (203, 'allowance_heat_work', 'Allowance Heat Work', '高温作业津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 20, 'direct_input', 'NUMBER', 0, NULL, '高温作业费', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (204, 'allowance_housing', 'Allowance Housing', '住房津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 21, 'direct_input', 'NUMBER', 0, NULL, 'HRA', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (205, 'allowance_lta', 'Allowance Lta', 'LTA津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 22, 'direct_input', 'NUMBER', 0, NULL, 'LTA', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (206, 'allowance_meal', 'Allowance Meal', '餐补', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 23, 'direct_input', 'NUMBER', 0, NULL, '伙食津貼  Allw Meal', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (207, 'allowance_other', 'Allowance Other', '其他津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 24, 'direct_input', 'NUMBER', 0, NULL, '其他津贴', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (208, 'allowance_project', 'Allowance Project', '项目津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 25, 'direct_input', 'NUMBER', 0, NULL, 'Project Allowance', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (209, 'allowance_remote', 'Allowance Remote', '远程办公津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 26, 'direct_input', 'NUMBER', 0, NULL, 'Remote Stipend', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (210, 'allowance_school', 'Allowance School', '教育津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 27, 'direct_input', 'NUMBER', 0, NULL, 'School Allowance', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (211, 'allowance_shift_mid', 'Allowance Shift Mid', '中班津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 28, 'direct_input', 'NUMBER', 0, NULL, '中班费', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (212, 'allowance_shift_night', 'Allowance Shift Night', '夜班津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 29, 'direct_input', 'NUMBER', 0, NULL, '夜班费', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (213, 'allowance_single_child', 'Allowance Single Child', '独生子女费', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 30, 'direct_input', 'NUMBER', 0, NULL, '独生子女费', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (214, 'allowance_special', 'Allowance Special', '特殊津贴', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 31, 'direct_input', 'NUMBER', 0, NULL, 'Special allowance', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (215, 'allowance_transport', 'Allowance Transport', '交通津贴（津贴/补贴）', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 32, 'direct_input', 'NUMBER', 0, NULL, '交通费', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 22:10:11', NULL);
INSERT INTO `portal_bill_field_info` VALUES (216, 'base_salary', 'Base Salary', '基本工资（Gross salary）', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 33, 'direct_input', 'NUMBER', 0, NULL, 'Base Salary', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-08 14:28:49', NULL);
INSERT INTO `portal_bill_field_info` VALUES (217, 'bonus', 'Bonus', '奖金', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 34, 'direct_input', 'NUMBER', 0, NULL, 'Bonus', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (218, 'bonus_annual', 'Bonus Annual', '13薪/年终奖', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 35, 'direct_input', 'NUMBER', 0, NULL, '13薪/年终奖', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (219, 'bonus_monthly', 'Bonus Monthly', '月奖', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 36, 'direct_input', 'NUMBER', 0, NULL, 'Monthly Bonus', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (220, 'bonus_other', 'Bonus Other', '其他奖金（日常奖金）', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 37, 'direct_input', 'NUMBER', 0, NULL, 'Other Bonus', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 22:08:41', NULL);
INSERT INTO `portal_bill_field_info` VALUES (221, 'bonus_quarterly', 'Bonus Quarterly', '季奖', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 38, 'direct_input', 'NUMBER', 0, NULL, '季奖', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (222, 'commission_bonus', 'Commission Bonus', '佣金/奖金', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 39, 'direct_input', 'NUMBER', 0, NULL, 'Commission /bonus', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (223, 'equity_incentive', 'Equity Incentive', '股权激励', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 40, 'direct_input', 'NUMBER', 0, NULL, '股权激励', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (224, 'gross_salary_subtotal', 'Subtotal', '应发工资小计', 2, 2, 'gross_salary', NULL, 0, 'subtotal', NULL, 'income_zone', 0, 0, 41, 'sum_children', 'NUMBER', 0, NULL, 'Subtotal', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 18:50:37', NULL);
INSERT INTO `portal_bill_field_info` VALUES (225, 'holiday_pay', 'Holiday Pay', '节假日工资', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 42, 'direct_input', 'NUMBER', 0, NULL, 'Holiday Pay', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (226, 'housing_fund_adjustment', 'Housing Fund Adjustment', '公积金调整', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 43, 'direct_input', 'NUMBER', 0, NULL, '公积金调整', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (227, 'incentive', 'Incentive', '激励', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 44, 'direct_input', 'NUMBER', 0, NULL, 'Incentives', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (228, 'leave_pay', 'Leave Pay', '假期工资', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 45, 'direct_input', 'NUMBER', 0, NULL, 'Leave Payment', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (229, 'net_adjustment', 'Net Adjustment', '净额调整', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 46, 'direct_input', 'NUMBER', 0, NULL, 'Net Adjustment', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (230, 'other_unspecified', 'Other Unspecified', '其他项', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 47, 'direct_input', 'NUMBER', 0, NULL, 'Other', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-03 16:51:18', NULL);
INSERT INTO `portal_bill_field_info` VALUES (231, 'overtime_pay', 'Overtime Pay', '加班费（Overtime Payment）', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 48, 'direct_input', 'NUMBER', 0, NULL, 'OT', NULL, '[]', 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-03 10:54:05', NULL);
INSERT INTO `portal_bill_field_info` VALUES (232, 'overtime_pay_1', 'Overtime Pay 1', '加班费1', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 49, 'direct_input', 'NUMBER', 0, NULL, 'OT1', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (233, 'overtime_pay_150', 'Overtime Pay 150', '加班费150%', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 50, 'direct_input', 'NUMBER', 0, NULL, '加班工资150', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (234, 'overtime_pay_2', 'Overtime Pay 2', '加班费2', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 51, 'direct_input', 'NUMBER', 0, NULL, 'OT2', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (235, 'overtime_pay_200', 'Overtime Pay 200', '加班费200%', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 52, 'direct_input', 'NUMBER', 0, NULL, '加班工资200', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (236, 'overtime_pay_300', 'Overtime Pay 300', '加班费300%', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 53, 'direct_input', 'NUMBER', 0, NULL, '加班工资300', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (237, 'post_tax_addition', 'Post Tax Addition', '税后补发', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 54, 'direct_input', 'NUMBER', 0, NULL, '税后补', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (238, 'post_tax_deduction', 'Post Tax Deduction', '税后扣减', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 55, 'direct_input', 'NUMBER', 0, NULL, '税后扣', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (239, 'pre_tax_adjustment', 'Pre Tax Adjustment', '税前调整', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 56, 'direct_input', 'NUMBER', 0, NULL, '税前调整', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (240, 'retro_deduction', 'Retro Deduction', '补扣', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 57, 'direct_input', 'NUMBER', 0, NULL, '补扣', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (241, 'retro_pay', 'Retro Pay', '补发薪资', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 58, 'direct_input', 'NUMBER', 0, NULL, 'Backpay', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (242, 'salary_adjustment', 'Salary Adjustment', '薪资调整', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 59, 'direct_input', 'NUMBER', 0, NULL, 'Salary Adjusment', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (243, 'severance_pay', 'Severance Pay', '离职补偿/赔偿金', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 60, 'direct_input', 'NUMBER', 0, NULL, '离职补偿金/赔偿金', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (244, 'social_security_adjustment', 'Social Security Adjustment', '社保调整', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 61, 'direct_input', 'NUMBER', 0, NULL, '社保调整', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (245, 'todo_review', 'Todo Review', '待人工确认', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 62, 'direct_input', 'NUMBER', 0, NULL, '資遣費 Severance', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (246, 'unused_annual_leave_pay', 'Unused Annual Leave Pay', '未休年假折现', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 63, 'direct_input', 'NUMBER', 0, NULL, '特休結算 Untaken AL', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (247, 'variable_salary', 'Variable Salary', '浮动工资', 1, 2, 'gross_salary', NULL, 0, 'dynamic_income', NULL, 'income_zone', 0, 1, 64, 'direct_input', 'NUMBER', 0, NULL, '浮动工资', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (248, 'expense_claim', 'Expense Claim', '报销金额（Expense 报销款）', 1, 2, 'expense_items', NULL, 0, 'dynamic_expense', NULL, 'expense_zone', 0, 1, 65, 'direct_input', 'NUMBER', 0, NULL, 'Expense Claim', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 22:12:45', NULL);
INSERT INTO `portal_bill_field_info` VALUES (249, 'expense_claim_25pct', 'Expense Claim 25Pct', '报销25%部分', 1, 2, 'expense_items', NULL, 0, 'dynamic_expense', NULL, 'expense_zone', 0, 1, 66, 'direct_input', 'NUMBER', 0, NULL, '报销款25%', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (250, 'expense_claim_subtotal', 'Subtotal', '报销小计', 2, 2, 'expense_items', NULL, 0, 'subtotal', NULL, 'expense_zone', 0, 0, 67, 'sum_children', 'NUMBER', 0, NULL, 'Subtotal', NULL, NULL, 'admin', '2026-03-31 16:55:06', 'admin', '2026-04-01 18:55:57', NULL);
INSERT INTO `portal_bill_field_info` VALUES (251, 'deduction_absence', 'Deduction Absence', '旷工扣款', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 68, 'direct_input', 'NUMBER', 0, NULL, '扣旷工', NULL, NULL, 'admin', '2026-03-31 16:55:06', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (252, 'deduction_absence_join_leave', 'Deduction Absence Join Leave', '入离职缺勤扣款', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 69, 'direct_input', 'NUMBER', 0, NULL, '入离职缺勤扣', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (253, 'deduction_personal_leave', 'Deduction Personal Leave', '事假扣款', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 70, 'direct_input', 'NUMBER', 0, NULL, '扣事假', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (254, 'deduction_sick_leave', 'Deduction Sick Leave', '病假扣款', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 71, 'direct_input', 'NUMBER', 0, NULL, '扣病假', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (255, 'deduction_total', 'Subtotal', '其他扣款/扣款小计', 2, 2, 'contribution_items', NULL, 0, 'subtotal', NULL, 'contribution_zone', 0, 0, 72, 'sum_children', 'NUMBER', 0, NULL, 'Deduction', NULL, NULL, 'admin', '2026-03-31 16:55:07', 'admin', '2026-04-01 18:56:07', NULL);
INSERT INTO `portal_bill_field_info` VALUES (256, 'deduction_unpaid_leave', 'Deduction Unpaid Leave', '无薪假扣款', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 73, 'direct_input', 'NUMBER', 0, NULL, 'No Pay Leave', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (257, 'employee_contribution_2g_hi', 'Employee Contribution 2G Hi', '二代健保', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 74, 'direct_input', 'NUMBER', 0, NULL, '2G HI', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (258, 'employee_contribution_annuity', 'Employee Contribution Annuity', '年金', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 75, 'direct_input', 'NUMBER', 0, NULL, '年金', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (259, 'employee_contribution_eobi', 'Employee Contribution Eobi', 'EOBI缴费', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 76, 'direct_input', 'NUMBER', 0, NULL, 'E.O.B.I', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (260, 'employee_contribution_housing_fund', 'Employee Contribution Housing Fund', '公积金', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 77, 'direct_input', 'NUMBER', 0, NULL, '缴公积金', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (261, 'employee_contribution_li', 'Employee Contribution Li', '劳保/保险', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 78, 'direct_input', 'NUMBER', 0, NULL, 'LI', NULL, '[]', 'admin', '2026-03-31 16:55:07', 'admin', '2026-04-02 17:27:26', NULL);
INSERT INTO `portal_bill_field_info` VALUES (262, 'employee_contribution_medical', 'Employee Contribution Medical', '医疗保险', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 79, 'direct_input', 'NUMBER', 0, NULL, '缴医疗', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (263, 'employee_contribution_mpf', 'Employee Contribution Mpf', 'MPF员工缴费', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 80, 'direct_input', 'NUMBER', 0, NULL, 'MPF EE', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (264, 'employee_contribution_other', 'Employee Contribution Other', '员工缴费', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 81, 'direct_input', 'NUMBER', 0, NULL, 'EE', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (265, 'employee_contribution_pension', 'Employee Contribution Pension', '养老保险', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 82, 'direct_input', 'NUMBER', 0, NULL, '缴养老', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (266, 'employee_contribution_supp_housing_fund', 'Employee Contribution Supp Housing Fund', '补充公积金', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 83, 'direct_input', 'NUMBER', 0, NULL, '缴补充公积金（免税）', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (267, 'employee_contribution_unemployment', 'Employee Contribution Unemployment', '失业保险', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 84, 'direct_input', 'NUMBER', 0, NULL, '缴失业', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (268, 'employee_contribution_union_fee', 'Employee Contribution Union Fee', '工会费', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 85, 'direct_input', 'NUMBER', 0, NULL, '工会费', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (269, 'employer_borne_tax', 'Employer Borne Tax', '公司负担税项', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 86, 'direct_input', 'NUMBER', 0, NULL, '公司负税项', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (270, 'income_tax', 'Income Tax', '个税', 2, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 87, 'direct_input', 'NUMBER', 0, NULL, 'IIT', NULL, NULL, 'admin', '2026-03-31 16:55:07', 'admin', '2026-04-01 22:31:15', NULL);
INSERT INTO `portal_bill_field_info` VALUES (271, 'mandatory_contribution_subtotal', 'Subtotal', '法定缴费小计', 2, 2, 'contribution_items', NULL, 0, 'subtotal', NULL, 'contribution_zone', 0, 0, 88, 'sum_children', 'NUMBER', 0, NULL, 'Subtotal', NULL, NULL, 'admin', '2026-03-31 16:55:07', 'admin', '2026-04-01 18:56:30', NULL);
INSERT INTO `portal_bill_field_info` VALUES (272, 'npl_hours', 'Npl Hours', '无薪假时数', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 89, 'direct_input', 'NUMBER', 0, NULL, 'NPL Hours', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (273, 'payroll_tax', 'Payroll Tax', 'PAYE税', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 90, 'direct_input', 'NUMBER', 0, NULL, 'PAYE (Estimated)', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);
INSERT INTO `portal_bill_field_info` VALUES (274, 'professional_tax', 'Professional Tax', '职业税', 1, 2, 'contribution_items', NULL, 0, 'dynamic_contribution', NULL, 'contribution_zone', 0, 1, 91, 'direct_input', 'NUMBER', 0, NULL, 'Professional Tax', NULL, NULL, 'admin', '2026-03-31 16:55:07', NULL, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
