/*
 Navicat MySQL Data Transfer

 Source Server         : portal测试环境2.188
 Source Server Type    : MySQL
 Source Server Version : 80026
 Source Host           : 192.168.2.188:3306
 Source Schema         : nnroad_portal

 Target Server Type    : MySQL
 Target Server Version : 80026
 File Encoding         : 65001

 Date: 25/06/2026 09:53:17
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for portal_vendor_field_mapping
-- ----------------------------
DROP TABLE IF EXISTS `portal_vendor_field_mapping`;
CREATE TABLE `portal_vendor_field_mapping`  (
  `mapping_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `vendor_id` bigint NOT NULL COMMENT '供应商ID',
  `vendor_template` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '模板标识（原 supplier_template 改为 vendor_template）',
  `source_field` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源字段（供应商侧列名/字段）',
  `use_example_source_field` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1=中文名+source_field 一起识别；0=仅按中文名',
  `output_header` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '输出表头（展示用）',
  `field_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '系统字段编码（关联 portal_bill_field_info.field_code）',
  `field_name_en` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '英文名称（可冗余）',
  `parent_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '父字段编码',
  `parent_name_cn` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '父字段中文名',
  `insert_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '插入/写入名称（如目标列名/节点名）',
  `insert_order` int NULL DEFAULT 0 COMMENT '插入顺序',
  `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用 0否 1是',
  `is_fixed_value` tinyint NOT NULL DEFAULT 0 COMMENT '是否固定值 0否 1是',
  `fixed_value` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '固定值（is_fixed_value=1 时使用）',
  `target_data_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '目标数据类型',
  `target_display_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '目标展示路径（如 Sheet/区块/层级路径）',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `create_time` datetime NULL DEFAULT NULL,
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `update_time` datetime NULL DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`mapping_id`) USING BTREE,
  UNIQUE INDEX `uk_vendor_template_source_field`(`vendor_id`, `vendor_template`, `source_field`, `field_code`) USING BTREE,
  INDEX `idx_vendor`(`vendor_id`) USING BTREE,
  INDEX `idx_field_code`(`field_code`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 838 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '供应商字段映射总表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of portal_vendor_field_mapping
-- ----------------------------
INSERT INTO `portal_vendor_field_mapping` VALUES (595, 2, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 1, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (596, 2, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 2, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (597, 2, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 3, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (598, 2, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 4, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (599, 2, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 5, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (600, 2, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 6, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (601, 2, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 7, 1, 1, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:31', 'admin', '2026-04-07 15:15:59', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (602, 2, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 8, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (603, 2, NULL, 'Base Salary', 1, 'Base Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 9, 1, 0, NULL, 'decimal', 'Base Salary', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (604, 2, NULL, 'OT', 1, 'OT', 'overtime_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 10, 1, 0, NULL, 'decimal', 'OT', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (605, 2, NULL, 'Salary Adjusment', 1, 'Salary Adjusment', 'salary_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 11, 1, 0, NULL, 'decimal', 'Salary Adjusment', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (606, 2, NULL, 'Bonus', 1, 'Bonus', 'bonus', NULL, 'gross_salary', 'Gross Salary', NULL, 12, 1, 0, NULL, 'decimal', 'Bonus', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (607, 2, NULL, 'Leave Payment', 1, 'Leave Payment', 'leave_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 13, 1, 0, NULL, 'decimal', 'Leave Payment', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (608, 2, NULL, 'Backpay', 1, 'Backpay', 'retro_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 14, 1, 0, NULL, 'decimal', 'Backpay', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (609, 2, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 15, 1, 0, NULL, 'decimal', 'Other', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (610, 2, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 16, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (611, 2, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 17, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (612, 2, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 18, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (613, 2, NULL, 'EE', 1, 'EE', 'employee_contribution_other', NULL, 'contribution_items', 'Contribution Items', NULL, 19, 1, 0, NULL, 'decimal', 'EE', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (614, 4, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 20, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (615, 4, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 21, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (616, 4, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 22, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (617, 4, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 23, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (618, 4, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 24, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (619, 4, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 25, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (620, 4, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 26, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (621, 4, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 27, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (622, 4, NULL, 'Basic salary', 1, 'Basic salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 28, 1, 0, NULL, 'decimal', 'Basic salary', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (623, 4, NULL, 'HRA', 1, 'HRA', 'allowance_housing', NULL, 'gross_salary', 'Gross Salary', NULL, 29, 1, 0, NULL, 'decimal', 'HRA', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (624, 4, NULL, 'Telephone allowance', 1, 'Telephone allowance', 'allowance_communication', NULL, 'gross_salary', 'Gross Salary', NULL, 30, 1, 0, NULL, 'decimal', 'Telephone allowance', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (625, 4, NULL, 'LTA', 1, 'LTA', 'allowance_lta', NULL, 'gross_salary', 'Gross Salary', NULL, 31, 1, 0, NULL, 'decimal', 'LTA', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (626, 4, NULL, 'Special allowance', 1, 'Special allowance', 'allowance_special', NULL, 'gross_salary', 'Gross Salary', NULL, 32, 1, 0, NULL, 'decimal', 'Special allowance', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (627, 4, NULL, 'Bonus', 1, 'Bonus', 'bonus', NULL, 'gross_salary', 'Gross Salary', NULL, 33, 1, 0, NULL, 'decimal', 'Bonus', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (628, 4, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 34, 1, 0, NULL, 'decimal', 'Other', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (629, 4, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 35, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (630, 4, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 36, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (631, 4, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 37, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (632, 4, NULL, 'Professional Tax', 1, 'Professional Tax', 'professional_tax', NULL, 'contribution_items', 'Contribution Items', NULL, 38, 1, 0, NULL, 'decimal', 'Professional Tax', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (633, 4, NULL, 'Deduction', 1, 'Deduction', 'deduction_total', NULL, 'contribution_items', 'Contribution Items', NULL, 39, 1, 0, NULL, 'decimal', 'Deduction', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (634, 4, NULL, 'IIT', 1, 'IIT', 'income_tax', NULL, 'contribution_items', 'Contribution Items', NULL, 40, 1, 0, NULL, 'decimal', 'IIT', 'admin', '2026-03-31 16:51:31', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (635, 6, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 41, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (636, 6, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 42, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (637, 6, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 43, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (638, 6, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 44, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (639, 6, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 45, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (640, 6, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 46, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (641, 6, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 47, 1, 1, '532845', 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:52:33', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (642, 6, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 48, 1, 1, '700000', 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:53:49', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (643, 6, NULL, 'Basic salary', 1, 'Basic salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 49, 1, 1, '700000', 'decimal', 'Basic salary', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 14:26:21', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (644, 6, NULL, 'Salary Adjusment', 1, 'Salary Adjusment', 'salary_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 50, 1, 1, '0', 'decimal', 'Salary Adjusment', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:55:47', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (645, 6, NULL, 'OT', 1, 'OT', 'overtime_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 51, 1, 1, '0', 'decimal', 'OT', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:56:51', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (646, 6, NULL, 'Monthly Bonus', 1, 'Monthly Bonus', 'bonus_monthly', NULL, 'gross_salary', 'Gross Salary', NULL, 52, 1, 1, '0', 'decimal', 'Monthly Bonus', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:56:57', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (647, 6, NULL, 'Other Bonus', 1, 'Other Bonus', 'bonus_other', NULL, 'gross_salary', 'Gross Salary', NULL, 53, 1, 1, '0', 'decimal', 'Other Bonus', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:57:05', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (648, 6, NULL, 'Leave Payment', 1, 'Leave Payment', 'leave_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 54, 1, 1, '0', 'decimal', 'Leave Payment', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:57:17', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (649, 6, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 55, 1, 1, '0', 'decimal', 'Other', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:24:11', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (650, 6, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 56, 1, 1, '0', 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:57:24', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (651, 6, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 57, 1, 1, '0', 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:57:38', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (652, 6, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 58, 1, 1, '167155', 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:58:13', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (653, 6, NULL, 'E.O.B.I', 1, 'E.O.B.I', 'employee_contribution_eobi', NULL, 'contribution_items', 'Contribution Items', NULL, 59, 1, 1, '370', 'decimal', 'E.O.B.I', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:58:38', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (654, 6, NULL, 'IT', 1, 'IT', 'income_tax', NULL, 'contribution_items', 'Contribution Items', NULL, 60, 1, 1, NULL, 'decimal', 'IT', 'admin', '2026-03-31 16:51:32', 'admin', '2026-04-02 13:58:58', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (655, 1, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 61, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (656, 1, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 62, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (657, 1, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 63, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (658, 1, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 64, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (659, 1, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 65, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (660, 1, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 66, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (661, 1, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 67, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (662, 1, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 68, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (663, 1, NULL, '基本工资', 1, '基本工资', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 69, 1, 0, NULL, 'decimal', '基本工资', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (664, 1, NULL, '浮动工资', 1, '浮动工资', 'variable_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 70, 1, 0, NULL, 'decimal', '浮动工资', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (665, 1, NULL, '月奖', 1, '月奖', 'bonus_monthly', NULL, 'gross_salary', 'Gross Salary', NULL, 71, 1, 0, NULL, 'decimal', '月奖', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (666, 1, NULL, '季奖', 1, '季奖', 'bonus_quarterly', NULL, 'gross_salary', 'Gross Salary', NULL, 72, 1, 0, NULL, 'decimal', '季奖', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (667, 1, NULL, '其他奖金', 1, '其他奖金', 'bonus_other', NULL, 'gross_salary', 'Gross Salary', NULL, 73, 1, 0, NULL, 'decimal', '其他奖金', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (668, 1, NULL, '加班工资150', 1, '加班工资150', 'overtime_pay_150', NULL, 'gross_salary', 'Gross Salary', NULL, 74, 1, 0, NULL, 'decimal', '加班工资150', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (669, 1, NULL, '加班工资200', 1, '加班工资200', 'overtime_pay_200', NULL, 'gross_salary', 'Gross Salary', NULL, 75, 1, 0, NULL, 'decimal', '加班工资200', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (670, 1, NULL, '加班工资300', 1, '加班工资300', 'overtime_pay_300', NULL, 'gross_salary', 'Gross Salary', NULL, 76, 1, 0, NULL, 'decimal', '加班工资300', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (671, 1, NULL, '入离职缺勤扣', 1, '入离职缺勤扣', 'deduction_absence_join_leave', NULL, 'contribution_items', 'Contribution Items', NULL, 77, 1, 0, NULL, 'decimal', '入离职缺勤扣', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (672, 1, NULL, '扣事假', 1, '扣事假', 'deduction_personal_leave', NULL, 'contribution_items', 'Contribution Items', NULL, 78, 1, 0, NULL, 'decimal', '扣事假', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (673, 1, NULL, '扣旷工', 1, '扣旷工', 'deduction_absence', NULL, 'contribution_items', 'Contribution Items', NULL, 79, 1, 0, NULL, 'decimal', '扣旷工', 'admin', '2026-03-31 16:51:32', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (674, 1, NULL, '扣病假', 1, '扣病假', 'deduction_sick_leave', NULL, 'contribution_items', 'Contribution Items', NULL, 80, 1, 0, NULL, 'decimal', '扣病假', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (675, 1, NULL, '交通费', 1, '交通费', 'allowance_transport', NULL, 'gross_salary', 'Gross Salary', NULL, 81, 1, 0, NULL, 'decimal', '交通费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (676, 1, NULL, '通讯费', 1, '通讯费', 'allowance_communication', NULL, 'gross_salary', 'Gross Salary', NULL, 82, 1, 0, NULL, 'decimal', '通讯费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (677, 1, NULL, '其他津贴', 1, '其他津贴', 'allowance_other', NULL, 'gross_salary', 'Gross Salary', NULL, 83, 1, 0, NULL, 'decimal', '其他津贴', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (678, 1, NULL, '中班费', 1, '中班费', 'allowance_shift_mid', NULL, 'gross_salary', 'Gross Salary', NULL, 84, 1, 0, NULL, 'decimal', '中班费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (679, 1, NULL, '夜班费', 1, '夜班费', 'allowance_shift_night', NULL, 'gross_salary', 'Gross Salary', NULL, 85, 1, 0, NULL, 'decimal', '夜班费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (680, 1, NULL, '高温费', 1, '高温费', 'allowance_heat', NULL, 'gross_salary', 'Gross Salary', NULL, 86, 1, 0, NULL, 'decimal', '高温费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (681, 1, NULL, '高温作业费', 1, '高温作业费', 'allowance_heat_work', NULL, 'gross_salary', 'Gross Salary', NULL, 87, 1, 0, NULL, 'decimal', '高温作业费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (682, 1, NULL, '有毒有害作业费', 1, '有毒有害作业费', 'allowance_hazard', NULL, 'gross_salary', 'Gross Salary', NULL, 88, 1, 0, NULL, 'decimal', '有毒有害作业费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (683, 1, NULL, '补发', 1, '补发', 'retro_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 89, 1, 0, NULL, 'decimal', '补发', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (684, 1, NULL, '补扣', 1, '补扣', 'retro_deduction', NULL, 'gross_salary', 'Gross Salary', NULL, 90, 1, 0, NULL, 'decimal', '补扣', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (685, 1, NULL, '税前调整', 1, '税前调整', 'pre_tax_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 91, 1, 0, NULL, 'decimal', '税前调整', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (686, 1, NULL, '公司负税项', 1, '公司负税项', 'employer_borne_tax', NULL, 'contribution_items', 'Contribution Items', NULL, 92, 1, 0, NULL, 'decimal', '公司负税项', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (687, 1, NULL, '独生子女费', 1, '独生子女费', 'allowance_single_child', NULL, 'gross_salary', 'Gross Salary', NULL, 93, 1, 0, NULL, 'decimal', '独生子女费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (688, 1, NULL, '外籍生活津贴', 1, '外籍生活津贴', 'allowance_expat', NULL, 'gross_salary', 'Gross Salary', NULL, 94, 1, 0, NULL, 'decimal', '外籍生活津贴', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (689, 1, NULL, '税后补', 1, '税后补', 'post_tax_addition', NULL, 'gross_salary', 'Gross Salary', NULL, 95, 1, 0, NULL, 'decimal', '税后补', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (690, 1, NULL, '税后扣', 1, '税后扣', 'post_tax_deduction', NULL, 'gross_salary', 'Gross Salary', NULL, 96, 1, 0, NULL, 'decimal', '税后扣', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (691, 1, NULL, '13薪/年终奖', 1, '13薪/年终奖', 'bonus_annual', NULL, 'gross_salary', 'Gross Salary', NULL, 97, 1, 0, NULL, 'decimal', '13薪/年终奖', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (692, 1, NULL, '离职补偿金/赔偿金', 1, '离职补偿金/赔偿金', 'severance_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 98, 1, 0, NULL, 'decimal', '离职补偿金/赔偿金', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (693, 1, NULL, '股权激励', 1, '股权激励', 'equity_incentive', NULL, 'gross_salary', 'Gross Salary', NULL, 99, 1, 0, NULL, 'decimal', '股权激励', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (694, 1, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 100, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (695, 1, NULL, '报销款', 1, '报销款', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 101, 1, 0, NULL, 'decimal', '报销款', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (696, 1, NULL, '报销款25%', 1, '报销款25%', 'expense_claim_25pct', NULL, 'expense_items', 'Expense Items', NULL, 102, 1, 0, NULL, 'decimal', '报销款25%', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (697, 1, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 103, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (698, 1, NULL, '缴养老', 1, '缴养老', 'employee_contribution_pension', NULL, 'contribution_items', 'Contribution Items', NULL, 104, 1, 0, NULL, 'decimal', '缴养老', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (699, 1, NULL, '缴医疗', 1, '缴医疗', 'employee_contribution_medical', NULL, 'contribution_items', 'Contribution Items', NULL, 105, 1, 0, NULL, 'decimal', '缴医疗', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (700, 1, NULL, '缴失业', 1, '缴失业', 'employee_contribution_unemployment', NULL, 'contribution_items', 'Contribution Items', NULL, 106, 1, 0, NULL, 'decimal', '缴失业', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (701, 1, NULL, '缴公积金', 1, '缴公积金', 'employee_contribution_housing_fund', NULL, 'contribution_items', 'Contribution Items', NULL, 107, 1, 0, NULL, 'decimal', '缴公积金', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (702, 1, NULL, '缴补充公积金（免税）', 1, '缴补充公积金（免税）', 'employee_contribution_supp_housing_fund', NULL, 'contribution_items', 'Contribution Items', NULL, 108, 1, 0, NULL, 'decimal', '缴补充公积金（免税）', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (703, 1, NULL, '社保调整', 1, '社保调整', 'social_security_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 109, 1, 0, NULL, 'decimal', '社保调整', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (704, 1, NULL, '公积金调整', 1, '公积金调整', 'housing_fund_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 110, 1, 0, NULL, 'decimal', '公积金调整', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (705, 1, NULL, '年金', 1, '年金', 'employee_contribution_annuity', NULL, 'contribution_items', 'Contribution Items', NULL, 111, 1, 0, NULL, 'decimal', '年金', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (706, 1, NULL, '工会费', 1, '工会费', 'employee_contribution_union_fee', NULL, 'contribution_items', 'Contribution Items', NULL, 112, 1, 0, NULL, 'decimal', '工会费', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (707, 1, NULL, 'Deduction', 1, 'Deduction', 'deduction_total', NULL, 'contribution_items', 'Contribution Items', NULL, 113, 1, 0, NULL, 'decimal', 'Deduction', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (709, 3, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 115, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (710, 3, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 116, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:33', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (711, 3, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 117, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (712, 3, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 118, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (713, 3, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 119, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (714, 3, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 120, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (715, 3, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 121, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (716, 3, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 122, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (717, 3, NULL, 'Base Salary', 1, 'Base Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 123, 1, 0, NULL, 'decimal', 'Base Salary', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (718, 3, NULL, 'OT', 1, 'OT', 'overtime_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 124, 1, 0, NULL, 'decimal', 'OT', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (719, 3, NULL, 'Salary Adjusment', 1, 'Salary Adjusment', 'salary_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 125, 1, 0, NULL, 'decimal', 'Salary Adjusment', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (720, 3, NULL, 'Bonus', 1, 'Bonus', 'bonus', NULL, 'gross_salary', 'Gross Salary', NULL, 126, 1, 0, NULL, 'decimal', 'Bonus', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (721, 3, NULL, 'Leave Payment', 1, 'Leave Payment', 'leave_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 127, 1, 0, NULL, 'decimal', 'Leave Payment', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (722, 3, NULL, 'Backpay', 1, 'Backpay', 'retro_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 128, 1, 0, NULL, 'decimal', 'Backpay', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (723, 3, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 129, 1, 0, NULL, 'decimal', 'Other', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (724, 3, NULL, 'Net Adjustment', 1, 'Net Adjustment', 'net_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 130, 1, 0, NULL, 'decimal', 'Net Adjustment', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (725, 3, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 131, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (726, 3, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 132, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (727, 3, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 133, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (728, 3, NULL, 'MPF EE', 1, 'MPF EE', 'employee_contribution_mpf', NULL, 'contribution_items', 'Contribution Items', NULL, 134, 1, 0, NULL, 'decimal', 'MPF EE', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (729, 5, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 135, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (730, 5, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 136, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (731, 5, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 137, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (732, 5, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 138, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (733, 5, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 139, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (734, 5, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 140, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (735, 5, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 141, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (736, 5, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 142, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (737, 5, NULL, 'Jul 2025 Salary', 1, 'Jul 2025 Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 143, 1, 0, NULL, 'decimal', 'Jul 2025 Salary', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (738, 5, NULL, 'Vacation Leave', 1, 'Vacation Leave', 'leave_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 144, 1, 0, NULL, 'decimal', 'Vacation Leave', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (739, 5, NULL, 'Bonus', 1, 'Bonus', 'bonus', NULL, 'gross_salary', 'Gross Salary', NULL, 145, 1, 0, NULL, 'decimal', 'Bonus', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (740, 5, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 146, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (741, 5, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 147, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (742, 5, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 148, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (743, 5, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 149, 1, 0, NULL, 'decimal', 'Other', 'admin', '2026-03-31 16:51:34', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (744, 5, NULL, 'Deduction', 1, 'Deduction', 'deduction_total', NULL, 'contribution_items', 'Contribution Items', NULL, 150, 1, 0, NULL, 'decimal', 'Deduction', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (745, 7, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 151, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (746, 7, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 152, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (747, 7, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 153, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (748, 7, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 154, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (749, 7, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 155, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (750, 7, NULL, 'To', 0, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 156, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:35', 'admin', '2026-04-03 13:53:35', NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (751, 7, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 157, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (752, 7, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 158, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (753, 7, NULL, 'Basic Salary', 1, 'Basic Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 159, 1, 0, NULL, 'decimal', 'Basic Salary', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (754, 7, NULL, 'Salary Adjustment', 1, 'Salary Adjustment', 'salary_adjustment', NULL, 'gross_salary', 'Gross Salary', NULL, 160, 1, 0, NULL, 'decimal', 'Salary Adjustment', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (755, 7, NULL, 'OT', 1, 'OT', 'overtime_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 161, 1, 0, NULL, 'decimal', 'OT', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (756, 7, NULL, 'Allw- Phone/ Communication', 1, 'Allw- Phone/ Communication', 'allowance_communication', NULL, 'gross_salary', 'Gross Salary', NULL, 162, 1, 0, NULL, 'decimal', 'Allw- Phone/ Communication', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (757, 7, NULL, 'Allw  Transportation', 1, 'Allw  Transportation', 'allowance_transport', NULL, 'gross_salary', 'Gross Salary', NULL, 163, 1, 0, NULL, 'decimal', 'Allw  Transportation', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (758, 7, NULL, 'Back Pay', 1, 'Back Pay', 'retro_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 164, 1, 0, NULL, 'decimal', 'Back Pay', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (759, 7, NULL, '伙食津貼  Allw Meal', 1, '伙食津貼  Allw Meal', 'allowance_meal', NULL, 'gross_salary', 'Gross Salary', NULL, 165, 1, 0, NULL, 'decimal', '伙食津貼  Allw Meal', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (760, 7, NULL, 'Remote Stipend', 1, 'Remote Stipend', 'allowance_remote', NULL, 'gross_salary', 'Gross Salary', NULL, 166, 1, 0, NULL, 'decimal', 'Remote Stipend', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (761, 7, NULL, '病假扣薪 Sick Leave (half pay)', 1, '病假扣薪 Sick Leave (half pay)', 'deduction_sick_leave', NULL, 'contribution_items', 'Contribution Items', NULL, 167, 1, 0, NULL, 'decimal', '病假扣薪 Sick Leave (half pay)', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (762, 7, NULL, 'NPL Hours', 1, 'NPL Hours', 'npl_hours', NULL, 'contribution_items', 'Contribution Items', NULL, 168, 1, 0, NULL, 'decimal', 'NPL Hours', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (763, 7, NULL, 'No Pay Leave', 1, 'No Pay Leave', 'deduction_unpaid_leave', NULL, 'contribution_items', 'Contribution Items', NULL, 169, 1, 0, NULL, 'decimal', 'No Pay Leave', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (764, 7, NULL, 'Bonus VB', 1, 'Bonus VB', 'bonus', NULL, 'gross_salary', 'Gross Salary', NULL, 170, 1, 0, NULL, 'decimal', 'Bonus VB', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (765, 7, NULL, 'Incentives', 1, 'Incentives', 'incentive', NULL, 'gross_salary', 'Gross Salary', NULL, 171, 1, 0, NULL, 'decimal', 'Incentives', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (766, 7, NULL, '特休結算 Untaken AL', 1, '特休結算 Untaken AL', 'unused_annual_leave_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 172, 1, 0, NULL, 'decimal', '特休結算 Untaken AL', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (767, 7, NULL, '資遣費 Severance', 1, '資遣費 Severance', 'todo_review', NULL, 'gross_salary', 'Gross Salary', NULL, 173, 1, 0, NULL, 'decimal', '資遣費 Severance', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (768, 7, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 174, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (769, 7, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 175, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (770, 7, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 176, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (771, 7, NULL, 'LI', 1, 'LI', 'employee_contribution_li', NULL, 'contribution_items', 'Contribution Items', NULL, 177, 1, 0, NULL, 'decimal', 'LI', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (772, 7, NULL, 'Pension', 1, 'Pension', 'employee_contribution_pension', NULL, 'contribution_items', 'Contribution Items', NULL, 178, 1, 0, NULL, 'decimal', 'Pension', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (773, 7, NULL, 'HI', 1, 'HI', 'employee_contribution_medical', NULL, 'contribution_items', 'Contribution Items', NULL, 179, 1, 0, NULL, 'decimal', 'HI', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (774, 7, NULL, '2G HI', 1, '2G HI', 'employee_contribution_2g_hi', NULL, 'contribution_items', 'Contribution Items', NULL, 180, 1, 0, NULL, 'decimal', '2G HI', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (775, 7, NULL, 'Deduction', 1, 'Deduction', 'deduction_total', NULL, 'contribution_items', 'Contribution Items', NULL, 181, 1, 0, NULL, 'decimal', 'Deduction', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (776, 7, NULL, 'IIT', 1, 'IIT', 'income_tax', NULL, 'contribution_items', 'Contribution Items', NULL, 182, 1, 0, NULL, 'decimal', 'IIT', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (777, 8, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 183, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (778, 8, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 184, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (779, 8, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 185, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:35', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (780, 8, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 186, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (781, 8, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 187, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (782, 8, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 188, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (783, 8, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 189, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (784, 8, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 190, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (785, 8, NULL, 'Basic Salary', 1, 'Basic Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 191, 1, 0, NULL, 'decimal', 'Basic Salary', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (786, 8, NULL, 'Housing Allowance', 1, 'Housing Allowance', 'allowance_housing', NULL, 'gross_salary', 'Gross Salary', NULL, 192, 1, 0, NULL, 'decimal', 'Housing Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (787, 8, NULL, 'Transport Allowance', 1, 'Transport Allowance', 'allowance_transport', NULL, 'gross_salary', 'Gross Salary', NULL, 193, 1, 0, NULL, 'decimal', 'Transport Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (788, 8, NULL, 'School Allowance', 1, 'School Allowance', 'allowance_school', NULL, 'gross_salary', 'Gross Salary', NULL, 194, 1, 0, NULL, 'decimal', 'School Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (789, 8, NULL, 'Mobile Allowance', 1, 'Mobile Allowance', 'allowance_communication', NULL, 'gross_salary', 'Gross Salary', NULL, 195, 1, 0, NULL, 'decimal', 'Mobile Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (790, 8, NULL, 'Food Allowance', 1, 'Food Allowance', 'allowance_meal', NULL, 'gross_salary', 'Gross Salary', NULL, 196, 1, 0, NULL, 'decimal', 'Food Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (791, 8, NULL, 'Other Allowance', 1, 'Other Allowance', 'allowance_other', NULL, 'gross_salary', 'Gross Salary', NULL, 197, 1, 0, NULL, 'decimal', 'Other Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (792, 8, NULL, 'OT1', 1, 'OT1', 'overtime_pay_1', NULL, 'gross_salary', 'Gross Salary', NULL, 198, 1, 0, NULL, 'decimal', 'OT1', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (793, 8, NULL, 'OT2', 1, 'OT2', 'overtime_pay_2', NULL, 'gross_salary', 'Gross Salary', NULL, 199, 1, 0, NULL, 'decimal', 'OT2', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (794, 8, NULL, 'Other Adjustments', 1, 'Other Adjustments', 'adjustment_other', NULL, 'gross_salary', 'Gross Salary', NULL, 200, 1, 0, NULL, 'decimal', 'Other Adjustments', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (795, 8, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 201, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (796, 8, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 202, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (797, 8, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 203, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (798, 8, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 204, 1, 0, NULL, 'decimal', 'Other', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (799, 8, NULL, 'Deduction', 1, 'Deduction', 'deduction_total', NULL, 'contribution_items', 'Contribution Items', NULL, 205, 1, 0, NULL, 'decimal', 'Deduction', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (800, 9, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 206, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (801, 9, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 207, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (802, 9, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 208, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (803, 9, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 209, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (804, 9, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 210, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (805, 9, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 211, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (806, 9, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 212, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (807, 9, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 213, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (808, 9, NULL, 'Basic Salary', 1, 'Basic Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 214, 1, 0, NULL, 'decimal', 'Basic Salary', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (809, 9, NULL, 'Housing Allowance', 1, 'Housing Allowance', 'allowance_housing', NULL, 'gross_salary', 'Gross Salary', NULL, 215, 1, 0, NULL, 'decimal', 'Housing Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (810, 9, NULL, 'Transport', 1, 'Transport', 'allowance_transport', NULL, 'gross_salary', 'Gross Salary', NULL, 216, 1, 0, NULL, 'decimal', 'Transport', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (811, 9, NULL, 'Other allowances', 1, 'Other allowances', 'allowance_other', NULL, 'gross_salary', 'Gross Salary', NULL, 217, 1, 0, NULL, 'decimal', 'Other allowances', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (812, 9, NULL, 'Project Allowance', 1, 'Project Allowance', 'allowance_project', NULL, 'gross_salary', 'Gross Salary', NULL, 218, 1, 0, NULL, 'decimal', 'Project Allowance', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (813, 9, NULL, 'Commission /bonus', 1, 'Commission /bonus', 'commission_bonus', NULL, 'gross_salary', 'Gross Salary', NULL, 219, 1, 0, NULL, 'decimal', 'Commission /bonus', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (814, 9, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 220, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (815, 9, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 221, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:36', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (816, 9, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 222, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (817, 9, NULL, 'Other', 1, 'Other', 'other_unspecified', NULL, 'gross_salary', 'Gross Salary', NULL, 223, 1, 0, NULL, 'decimal', 'Other', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (818, 9, NULL, 'Deduction', 1, 'Deduction', 'deduction_total', NULL, 'contribution_items', 'Contribution Items', NULL, 224, 1, 0, NULL, 'decimal', 'Deduction', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (819, 10, NULL, 'Client Code', 1, 'Client Code', 'client_code', NULL, 'base_info', '基础信息', NULL, 225, 1, 0, NULL, 'string', 'Client Code', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (820, 10, NULL, 'Client Name', 1, 'Client Name', 'client_name', NULL, 'base_info', '基础信息', NULL, 226, 1, 0, NULL, 'string', 'Client Name', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (821, 10, NULL, 'EE Code', 1, 'EE Code', 'employee_code', NULL, 'base_info', '基础信息', NULL, 227, 1, 0, NULL, 'string', 'EE Code', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (822, 10, NULL, 'EE Name', 1, 'EE Name', 'employee_name', NULL, 'base_info', '基础信息', NULL, 228, 1, 0, NULL, 'string', 'EE Name', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (823, 10, NULL, 'From', 1, 'From', 'pay_period_from', NULL, 'pay_period', '付款日期', NULL, 229, 1, 0, NULL, 'date', 'From', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (824, 10, NULL, 'To', 1, 'To', 'pay_period_to', NULL, 'pay_period', '付款日期', NULL, 230, 1, 0, NULL, 'date', 'To', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (825, 10, NULL, 'Net Income', 1, 'Net Income', 'net_income', NULL, 'net_income_group', 'Net Income', NULL, 231, 1, 0, NULL, 'decimal', 'Net Income', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (826, 10, NULL, 'Subtotal', 1, 'Subtotal', 'gross_salary_subtotal', NULL, 'gross_salary', 'Gross Salary', NULL, 232, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (827, 10, NULL, 'Basic Salary', 1, 'Basic Salary', 'base_salary', NULL, 'gross_salary', 'Gross Salary', NULL, 233, 1, 0, NULL, 'decimal', 'Basic Salary', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (828, 10, NULL, 'Holiday Pay', 1, 'Holiday Pay', 'holiday_pay', NULL, 'gross_salary', 'Gross Salary', NULL, 234, 1, 0, NULL, 'decimal', 'Holiday Pay', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (829, 10, NULL, 'Car Allowance', 1, 'Car Allowance', 'allowance_car', NULL, 'gross_salary', 'Gross Salary', NULL, 235, 1, 0, NULL, 'decimal', 'Car Allowance', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (830, 10, NULL, 'Subtotal', 1, 'Subtotal', 'expense_claim_subtotal', NULL, 'expense_items', 'Expense Items', NULL, 236, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (831, 10, NULL, 'Expense Claim', 1, 'Expense Claim', 'expense_claim', NULL, 'expense_items', 'Expense Items', NULL, 237, 1, 0, NULL, 'decimal', 'Expense Claim', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (832, 10, NULL, 'Subtotal', 1, 'Subtotal', 'mandatory_contribution_subtotal', NULL, 'contribution_items', 'Contribution Items', NULL, 238, 1, 0, NULL, 'decimal', 'Subtotal', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (833, 10, NULL, 'PAYE (Estimated)', 1, 'PAYE (Estimated)', 'payroll_tax', NULL, 'contribution_items', 'Contribution Items', NULL, 239, 1, 0, NULL, 'decimal', 'PAYE (Estimated)', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (834, 10, NULL, 'EE\'NIC', 1, 'EE\'NIC', 'todo_review', NULL, 'gross_salary', 'Gross Salary', NULL, 240, 1, 0, NULL, 'decimal', 'EE\'NIC', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (835, 10, NULL, 'EE\' Pension  (Auto Enrolment)', 1, 'EE\' Pension  (Auto Enrolment)', 'todo_review', NULL, 'gross_salary', 'Gross Salary', NULL, 241, 1, 0, NULL, 'decimal', 'EE\' Pension  (Auto Enrolment)', 'admin', '2026-03-31 16:51:37', NULL, NULL, NULL);
INSERT INTO `portal_vendor_field_mapping` VALUES (836, 1, NULL, 'IIT', 1, '', 'IIT', '', '', '', '', 100, 1, 0, NULL, '', '', 'admin', '2026-04-01 22:23:05', NULL, NULL, '');
INSERT INTO `portal_vendor_field_mapping` VALUES (837, 1, NULL, 'IIT', 1, '', 'IIT', '', '', '', '', 100, 1, 0, NULL, '', '', 'admin', '2026-04-01 22:23:50', NULL, NULL, '');

SET FOREIGN_KEY_CHECKS = 1;
